### ISSUE TITLE
Snowboy 

### ISSUE THREAD

**Issue by Sean-Amor** [RyanMCole/PiZeroSnowboy#1]
Thank you for this, I'll give it a shot, I have spent a month trying every walk through online and none have worked. Perhaps if I am unsuccessful, you'd have time to make a copy of your os, with a working snowboy? Maybe dropbox, or Google drive or something of your choice? Raspberry Pi Zero W.  I'm trying to make a Harry Potter themed led light for my car. "Lumos" turns on the led light, followed by a custom sound wav file. "Nox" turns off the led light, again followed by a custom sound wav file. I already have a trained pmdl file, along with the wav sound files. And I would be using a ps eye possibly for the mic.

**Comment by RyanMCole** [comment]
This was more of a learning experience than a success in getting a working project, so I recommend using a non-zero Pi for any voice activated work. In my opinion, the limited amount of inputs and outputs on the Pi Zero is just too much of a hurdle. Anyway, here is an image of a working OS: https://drive.google.com/open?id=1xaG9LfnDC-Q5qixC3dxeEXwvM_zpNGH9

**Comment by Sean-Amor** [comment]
Thanks! I appreciate it, im assuming I can just burn this with Etcher. I plan to get a Rpi3B+ eventually, so this is very useful.

**Comment by RyanMCole** [comment]
You're welcome. Yes, Etcher was the image writing software I used too. The image might also work with other Pi models with tweaking, but if you're going that route it would be better to follow the Snowboy official guideline for a fresh start.

**Comment by Sean-Amor** [comment]
Okay, thanks! Before your img, I had successfully gotten Snowboy setup on a Pi0(with your instructions), but then had the issue with the PS3 Eye, and ALSA, apparently more recent Raspbian img's broke ALSA for this device, and for some reason the img from 2016 that allegedly works, cant even write to the pi0, at least not for me.

Im sure the Pi 3B+ will be more successful once purchased, and have less issues on installation.

**Comment by Sean-Amor** [comment]
All works now, I bought a lapel mic, and a usb sound card. 
However I was wondering if you had any experience in combining other scripts together with your sound file script.
https://drive.google.com/open?id=1F6mI_wJ4Bc_WWxwpn_CQANhQGnkRkw23

I have it where I say "Lumos" then it plays the sound file, and "Nox" then that sound file.
I would love to say the command, have it play the sound, then turn on a gpio pin for an led, then I say the other command then it turns it off.

I have found tons of examples on flashing an led but id prefer it stay on till I say otherwise, also not sure how to have include it within the sound script you made.

Your snowboy.py modified to work with my sound files:
https://hastebin.com/ajecewiwos.py

Your snowboydecoder.py modified to work with my sound files:
https://hastebin.com/atikicovac.py
